config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  root 'pages#landing'
  get 'pages/about'
  get 'profiles/my_photos'
  get 'profiles/subscribes_list'
  get 'profiles/friends_photos'  
  get 'profiles/:id' => 'profiles#show', as: "profile"
  get 'profiles/:id/subscribe' => 'profiles#subscribe', as: 'subscribe_profile'
  get 'profiles/:id/unsubscribe' => 'profiles#unsubscribe', as: 'unsubscribe_profile'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :user;
    has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" };
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  	validates :description, presence: true;
  	validates :image, presence: true;
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates :name, presence: true;
  has_many :photos;
  has_many :subscriptions;
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  def set_locale
  	I18n.locale = extract_locale_from_accept_language_header
  end  

  private

  def extract_locale_from_accept_language_header
  	http_accept_language = request.env['HTTP_ACCEPT_LANGUAGE']
	if http_accept_language
		case http_accept_language.scan(/^[a-z]{2}/).first
			when 'en'
				'en'
			when 'ru'
				'ru'
			else 'ru'
		end
	else
		'ru'
	end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
  	if user_signed_in?
  		redirect_to "/photos"
  	end
  end

  def about
  end  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :owner, only: [:edit, :update, :destroy]

  def index
    @photos = Photo.all.order('created_at desc').paginate(:page => params[:page], :per_page => 6)
  end

  def show
  end

  def new
    @photo = current_user.photos.build
  end

  def edit
  end

  def create
    @photo = current_user.photos.build(photo_params)

    if @photo.save
      redirect_to @photo, notice: t('photos.notices.created')
    else
      render :new
    end
  end

  def update
    if @photo.update(photo_params)
      redirect_to @photo, notice: t('photos.notices.updated')
    else
      render :edit
    end
  end

  def destroy
    @photo.destroy
      redirect_to photos_url, notice: t('photos.notices.deleted')
  end

  private
    def owner
      @photo = current_user.photos.find_by(id: params[:id])
      redirect_to photos_path, notice: t('photos.notices.havent_got_rights') if @photo.nil?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:description, :image)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :set_user, except: [:my_photos, :subscribes_list, :friends_photos];
	before_action :authenticate_user!, except: [:show];

  def show
  	@photos = @user.photos.paginate(:page => params[:page], :per_page => 6)
  end  

def subscribe
	if current_user.id == @user.id
		redirect_to profile_path(@user), notice: t('profiles.notices.cant_subscr_to_yourself')
	else
		if current_user.subscriptions.exists?(friend_id: @user.id)
			redirect_to profile_path(@user), notice: t('profiles.notices.subscr_to_user_already')
		else
			@subscription = current_user.subscriptions.build
			@subscription.friend_id = @user.id
			@subscription.save
			if @subscription.save
				redirect_to profile_path(@user), notice: t('profiles.notices.succ_subscr_to_user')
			end
		end
	end
end

def unsubscribe
	if current_user.id == @user.id
		redirect_to profile_path(@user), notice: t('profiles.notices.cant_subscr_to_yourself')
	else	
		if current_user.subscriptions.exists?(friend_id: @user.id)
			@subscription = current_user.subscriptions.find_by_friend_id(@user.id)
			@subscription.destroy
			redirect_to profile_path(@user), notice: t('profiles.notices.succ_unsubscr_to_user')
		else
			redirect_to profile_path(@user), notice: t('profiles.notices.werent_subscr_to_user')
		end
	end
end

def my_photos
	@photos = current_user.photos.order('created_at desc').paginate(:page => params[:page], :per_page => 6)
end

def subscribes_list
	@friends = User.where(id: current_user.subscriptions.pluck(:friend_id))
end

def friends_photos
	@photos = Photo.where(user_id: current_user.subscriptions.pluck(:friend_id)).order('created_at desc').paginate(:page => params[:page], :per_page => 6)
end

  private
    def set_user
      @user = User.find(params[:id])
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pagination_helper.rb
require "will_paginate/view_helpers/action_view"

module PaginationHelper

  module BootstrapRenderer

    def to_html
      html = pagination.map do |item|
        item.is_a?(Fixnum) ?
          page_number(item) :
          send(item)
      end.join(@options[:link_separator])

      html = html_container(html) if @options[:container]

      tag("nav", tag("ul", html, class: @options[:class]))
    end

    protected

    def page_item(text, url, link_status = nil)
      text = text.to_s + tag(:span, "(current)", class: "sr-only") if link_status == "active"
      link_tag = link_status.nil? ? link(text, url, class: "page-link", rel: text) : tag(:span, text, class: "page-link")

      tag(:li, link_tag, class: "page-item #{link_status}")
    end

    def page_number(page)
      link_status = "active" if page == current_page
      page_item(page, page, link_status)
    end

    def gap
      text = @template.will_paginate_translate(:page_gap) { '&hellip;' }
      page_item(text, nil, "disabled")
    end

    def previous_page
      num = @collection.current_page > 1 && @collection.current_page - 1
      previous_or_next_page(num, @options[:previous_label], "Previous")
    end

    def next_page
      num = @collection.current_page < total_pages && @collection.current_page + 1
      previous_or_next_page(num, @options[:next_label], "Next")
    end

    def previous_or_next_page(page, text, aria_label)
      link_status = "disabled" unless page
      page_item(text, page, link_status)
    end
  end
end

WillPaginate::ActionView::LinkRenderer.send :include, PaginationHelper::BootstrapRenderer

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container">
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <%= link_to "Instaphoto", root_path, class:'navbar-brand text-logo' %>    
        <ul class="navbar-nav">
         <li class="nav-item">
            <%= link_to t('navigation.about'), pages_about_path, class:'nav-link' %>
          </li>          
          <li class="nav-item">
            <%= link_to t('navigation.upload'), new_photo_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to t('navigation.friends_photos'), profiles_friends_photos_path, class:'nav-link' %>
          </li>           
         </ul>
        <div class="btn-group ml-auto mt-2 mt-lg-0 navbar-nav">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
          </button>
          <div class="dropdown-menu dropdown-menu-right">
            <%= link_to t('navigation.account'), edit_user_registration_path, class:'dropdown-item' %>
            <%= link_to t('navigation.my_photos'), profiles_my_photos_path, class:'dropdown-item' %>
            <%= link_to t('navigation.my_subscriptions'), profiles_subscribes_list_path, class:'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to t('navigation.logout'), destroy_user_session_path, method: :delete, class:'dropdown-item' %>
          </div>
        </div>
      </div>
    </div>
  </nav>
<% else %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-trasparent">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container">
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <%= link_to "Instaphoto", root_path, class:'navbar-brand text-logo .landing-logo' %>    
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <%= link_to t('navigation.photos'), photos_path, class:'nav-link' %>
          </li>          
          <li class="nav-item">
            <%= link_to t('navigation.about'), pages_about_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to t('navigation.login'), new_user_session_path, class:'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaphoto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if user_signed_in? %>
		  <div class="container-fluid container-login">  		
  	<% else %>
  		<div class="container-fluid container-background container-login">
  	<% end %>
  	 		<%= render "layouts/navigation"%>  		
    		<div class="container">
    	        <p class="notice"><%= notice %></p>
    	        <p class="alert"><%= alert %></p>				
    			<%= yield %>
    		</div>
      </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= t('about.title') %></h1>
  <p class="lead"><%= t('about.description') %></p>
</div>

app/views/pages/landing.html.erb
<% if user_signed_in? %>
<% else %>
	<div class="jumbotron">
	  <h1 class="display-4"><%= t('landing.header') %></h1>
	  <p class="lead"><%= t('landing.description') %></p>
	  <hr class="my-4">
	  <p class="lead">
	  	<%= link_to t('landing.buttons.create_account'), new_user_registration_path, class: "btn btn-danger" %>
	  	<%= link_to t('landing.buttons.login'), new_user_session_path, class: "btn btn-info" %>
	  </p>
	</div>
<% end %>

app/views/photos/_form.html.erb
<%= form_for photo, html: { multipart: true } do |f| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t('photos.other.image') %>
    <%= f.file_field :image, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label t('photos.other.description') %>
    <%= f.text_field :description, class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class="card photo-form">
  <div class="card-header">
    <h2><%= t('photos.titles.edit') %></h2>
  </div>
  <div class="card-body">
	<%= render 'form', photo: @photo %>

	<%= link_to t('photos.links.show'), @photo %> |
	<%= link_to t('photos.links.back'), photos_path %>
  </div>
</div>	

app/views/photos/index.html.erb
<% @photos.each do |photo| %>
  <div class="card photo-form mb-3">
    <div class="card-body">
      <div class="img-container">
        <%= link_to photo, class: 'photo-link' do %>
          <%= image_tag photo.image.url(:medium), class: 'img' %>
        <% end %>
      </div>
      <br>
      <strong><%= photo.description %></strong>
      <br>
      <%= link_to profile_path(photo.user_id) do %>
        <i class="ion-person"></i>
        <%= photo.user.name %>  
      <% end %>    
      <% if photo.user == current_user %>
        <span class="float-right">
          <%= link_to edit_photo_path(photo) do %><i class="ion-edit"></i> <%= t('photos.links.edit')%><% end %> |
          <%= link_to photo, method: :delete, data: { confirm: t('photos.other.are_you_sure') } do %><i class="ion-trash-b"></i> <%= t('photos.links.delete')%><% end %>
        </span>
      <% end %>  
    </div> 
  </div> 
<% end %>

<%= will_paginate @photos, class:"pagination justify-content-center" %>

app/views/photos/new.html.erb
<div class="card photo-form">
  <div class="card-header">
    <h2><%= t('photos.titles.new') %></h2>
  </div>
  <div class="card-body">
	<%= render 'form', photo: @photo %>

	<%= link_to t('photos.links.back'), photos_path %>
  </div>
</div>

app/views/photos/show.html.erb
<div class="card photo-form">
  <div class="card-body">
	<%= image_tag @photo.image.url(:large) %>
	<br>
	<strong><%= @photo.description %></strong>
	<br>
	<%= link_to profile_path(@photo.user_id) do %>
	<i class="ion-person"></i>
	<%= @photo.user.name %>  
	<% end %>
	<% if @photo.user == current_user %>
        <span class="float-right">
          <%= link_to edit_photo_path(@photo) do %><i class="ion-edit"></i> <%= t('photos.links.edit')%><% end %> |
          <%= link_to @photo, method: :delete, data: { confirm: t('photos.other.are_you_sure') } do %><i class="ion-trash-b"></i> <%= t('photos.links.delete')%><% end %>
        </span>
	<% end %>
  </div>
</div>

app/views/profiles/friends_photos.html.erb
<% @photos.each do |photo| %>
  <div class="card photo-form mb-3">
    <div class="card-body">
      <div class="img-container">
        <%= link_to photo, class: 'photo-link' do %>
          <%= image_tag photo.image.url(:medium) %>
        <% end %>
      </div> 
      <br>
      <strong><%= photo.description %></strong>
      <br>
      <%= link_to profile_path(photo.user_id) do %>
        <i class="ion-person"></i>
        <%= photo.user.name %>  
      <% end %> 
    </div> 
  </div> 
<% end %>

<%= will_paginate @photos, class:"pagination justify-content-center" %>

app/views/profiles/my_photos.html.erb
<% @photos.each do |photo| %>
  <div class="card photo-form mb-3">
    <div class="card-body">
      <div class="img-container">
        <%= link_to photo, class: 'photo-link' do %>
          <%= image_tag photo.image.url(:medium) %>
        <% end %>
      </div>
      <br>
      <strong><%= photo.description %></strong>
      <br>
      <%= link_to edit_photo_path(photo) do %><i class="ion-edit"></i> <%= t('photos.links.edit') %><% end %> |
      <%= link_to photo, method: :delete, data: { confirm: t('photos.other.are_you_sure') } do %><i class="ion-trash-b"></i> <%= t('photos.links.delete') %><% end %>
    </div> 
  </div> 
<% end %>

app/views/profiles/show.html.erb
<h2><%= @user.name %></h2>

<% if current_user.id == @user.id %>
<% else %>
  <% if current_user.subscriptions.exists?(friend_id: @user.id) %>
    <%= link_to t('profiles.buttons.unsubscribe'), unsubscribe_profile_path(@user), class: 'btn btn-primary' %>
  <% else %>
    <%= link_to t('profiles.buttons.subscribe'), subscribe_profile_path(@user), class: 'btn btn-primary' %>
  <% end %>
<% end %>  
<br>
<br>
<% @photos.each do |photo| %>
  <div class="card photo-form mb-3">
    <div class="card-body photo-link">
      <div class="img-container">
        <%= link_to photo, class: 'photo-link' do %>
          <%= image_tag photo.image.url(:medium) %>
        <% end %>
      </div>
      <br>
      <strong><%= photo.description %></strong>
      <br>
      <% if photo.user == current_user %>
        <%= link_to edit_photo_path(photo) do %><i class="ion-edit"></i> <%= t('photos.links.edit') %><% end %> |
        <%= link_to photo, method: :delete, data: { confirm: t('photos.other.are_you_sure') } do %><i class="ion-trash-b"></i> <%= t('photos.links.delete') %><% end %>
      <% end %>  
    </div> 
  </div> 
<% end %>

app/views/profiles/subscribes_list.html.erb
<% @friends.each do |friend| %>
  <div class="card photo-form mb-3">
    <div class="card-body">
      <%= link_to friend.email, profile_path(friend.id) %> |
      <%= link_to t('profiles.links.unsubscribe'),unsubscribe_profile_path(friend.id) %>
    </div> 
  </div> 
  <br>
<% end %>